language: haskell

script:
  - cabal install --only-dependencies && cabal configure && cabal build

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update
  - cabal install bmp-head/
install:
  - cabal install --force-reinstalls
  
notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#hnn"
