language: haskell

script:
  - cabal install --only-dependencies && cabal configure && cabal build

ghc:
  - 7.8

notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#haskell-math"
